### ISSUE TITLE
How to use pool

### ISSUE THREAD

**Issue by BarryRufer** [SiroDiaz/sphinxql#4]
Hello.

> not the most recommended, use a pool connection

Example?

**Comment by SiroDiaz** [comment]
Hello @BarryRufer.
I'm going to write in README about how to create a pool connection. Basically use `createPoolConnection` instead of `createConnection` 

> because connection pools help reduce the time spent connecting to MySQL server.

You must know that createPoolConnection accepts more options than createConnection such as `waitForConnections` and more. For more information about configuration pool connections go to [mysql2 documentation about using connection pools](https://www.npmjs.com/package/mysql2#using-connection-pools)

Example of createPoolConnection:
```js
const sphql = Sphinxql.createPoolConnection({
  host: 'localhost',
  port: 9306,
  waitForConnections: true,
  connectionLimit: 10,
  queueLimit: 0
});
```

**Comment by BarryRufer** [comment]
Thank you, I will try to put this into practice.
